### PR TITLE
Add Some Improvement

### PR DESCRIPTION
**Pull request by dimaslanjaka**
- add auto default template
- add missing docs
- add me as contributor
- add `redirect_to` property for canonical metadata
- add string support on `redirect_from` property

### CODE REVIEW

**Comment by dimaslanjaka** [comment]
- add string support on `redirect_from` property

**Review by sergeyzwezdin — CHANGES_REQUESTED** [review]
@dimaslanjaka thank you for your efforts, but I cannot accept the changes how looks now. Please, fix the following things so I can move forward with it:
1. Github Workflow file rename - `why need this`?
2. Restore `.nvmrc`
3. Restore prettier/eslint settings file
4. Revert anything related to vscode settings
5. Revert tab/spacing settings back
6. Make PR name more verbose / define a goal of the PR
7. Ideally, the PR should be granular and follow the one single goal, if need fix more than one things - create a few PRs

**Comment by sergeyzwezdin** [comment]
As I mentioned, to understand your changes PR should be more atomic and follow the single goal. So if you need these changes, please put them into a few separate PR with proper title/description. Because that closing this PR.

**Comment by dimaslanjaka** [comment]
> @dimaslanjaka thank you for your efforts, but I cannot accept the changes how looks now. Please, fix the following things so I can move forward with it:
> 
>     1. Github Workflow file rename - `why need this`?
> 
>     2. Restore `.nvmrc`
> 
>     3. Restore prettier/eslint settings file
> 
>     4. Revert anything related to vscode settings
> 
>     5. Revert tab/spacing settings back
> 
>     6. Make PR name more verbose / define a goal of the PR
> 
>     7. Ideally, the PR should be granular and follow the one single goal, if need fix more than one things - create a few PRs

point 7: so I have to make one by one pull request every improv I make?

**Comment by sergeyzwezdin** [comment]
@dimaslanjaka correct, also please describe properly every change you do

**Pull request closed without merging**
